---
title: "2012 animes"
description: |
  The following blog will be about the top anime of 2012.
author:
  - name: Demetrio Munoz
date: 05-26-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# The following list of anime are coe from 2012 series some of the anime that will be mentioned are on going. 



























```{r}
#the following data will be created for the top anime for 2012
#created the objected called anime name.
animename<- c("JoJo's Bizzare Adventure","Sword are","Kurokos's Basketball", "Psycho-Pass",
              "Another",
              "Magi: The labyrinth of Magic",
              "Kamishama hajimemashita",
              "K", "Nisemonogatari",
              "Joshiraku",
              "Star Blazers 2199",
              "Girl und Panzer",
              "Nyaruko: Crawling with Love",
              "Medaka Box","Zetman",
              "Uchû kyôdai",
              "Aquarion EVOL",
              "Bodacious Space Pirates ",
              "Terumae romae",
              "Wooser no Sono Higurashi")
```

```{r}
# The following code line will be created to store the data for ranking from 1-20
ranking<- c(1:20)
anime.list <- list(anime =animename,place = ranking)
```


