---
title: "Tidytuesday-Videogames"
description: |
  Tidytuesday videogame graph.
draft: true
author:
  - name: Demetrio Munoz 
date: 05-01-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Libraries that will be used for this data Analysis 
```{r}
library(tidytuesdayR)
library(tidyverse)
library(scales)
library(lubridate)
library(plotly)
theme_set(theme_light())
```

# Import data
```{r}
tt<- tt_load("2021-03-16")

```
 
 
  1 because every first of the month

```{r}
tibble(date = seq(as.Date("2020-01-01"),as.Date("2020-12-31"),1)) %>% 
  mutate(month_number = month(date))



games<-tt$games %>% 
  mutate(avg_peak_perc = parse_number(avg_peak_perc)/100) %>%
  mutate(date = ymd(paste(year,month,1))) %>%
  filter(date > min(date)) %>%
  mutate(month = fct_reorder(month,month(date)))
         
```


# working with the variable year recreate the variable to be more vizual. Turning month into number

  This tracks games over time
  
```{r}
games %>% 
  count(date) %>% 
  ggplot(aes(date,n)) + 
  geom_col()

summarize_games <- function(tbl) {
  tbl %>%
    summarize(median_avg = median(avg),
              median_peak = median(peak))
}

# average number of players at any point
#games %>% 
  #group_by(date) %>% 
  #ggplot(aes(date, median_avg)) +
  #geom_line() + 
  #expand_limits(y = 0) + 
  #labs(x = "Month",
       #y = "Median Popularity of game on steam")
  

# Spikes during summer, slow during school year
games %>% 
  filter(date< "2020-01-01") %>% 
  group_by(month) %>%
  summarize_games() %>%
  ggplot(aes(month, median_avg)) + 
  geom_line(group = 1) + 
  expand_limits(y = 0) + 
  labs(x = "Month of year",
       y= "Mediian popularity of a game on steam", 
       title = "Seasonal trend in steam games",
       subtitle = "From 2012 - 2019")

games %>% 
  group_by(year, month) %>% 
  summarize_games() %>%
  ggplot(aes(month, median_avg)) + 
  geom_line(aes(color = factor(year), group = year)) + 
  expand_limits(y = 0) + 
  labs(x = "Month of year",
       y= "Mediian popularity of a game on steam", 
       title = "Seasonal trend in steam games",
       color = "Year")


games %>% 
  group_by(date) %>%
  summarize_games() %>%
  ggplot(aes(date,median_peak)) + 
  geom_line() + 
  expand_limits(y = 0)
```
